#!/bin/bash

add_to_path "$HOME/local/bin"

alias grep='grep --color=auto -i'

alias la='ls -a'
alias ll='ls -l'
alias remux='ffmpeg -vcodec copy -acodec copy -i'
alias unset.executable.bit.for.regular.files='find . -type f -print0 | xargs -0 chmod -x'
alias convert.new.lines.to.nul="tr '\n' '\0'"
alias tree.for.exchange.dropboxes="tree -I 'Icon*' --prune --noreport -N -F"

alias serve.this='mongoose -x ".DS_Store"'

export EDITOR=mvim

alias p4merge='/Applications/p4merge.app/Contents/Resources/launchp4merge'

alias fix.open.with='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'
