#!/bin/bash

# Page more conveniently and with more color
vim_less="vim -u /usr/share/vim/vim73/macros/less.vim"
alias less="$vim_less"
export MANPAGER="col -b | $vim_less -c 'set ft=man nomod nolist' -"
