#!/bin/bash

export BASH_COMPLETION_DIR="$HOME/local/bash_completion.d"
for i in $(LC_ALL=C command ls "$BASH_COMPLETION_DIR"); do
    source "$BASH_COMPLETION_DIR/$i"
done

# For sudo this is a stupid solution. But still.
complete -c which man sudo

# Complete ssh from recently used hosts
complete -W "$(echo $(grep '^ssh ' ~/.bash_history | sort -u | sed 's/^ssh //'))" ssh
