#!/bin/bash

eval "$(rbenv init -)"

__rbenv_version_no() {
    echo $1 | sed -e 's/ .*//'
}

__rbenv_global_version=$(__rbenv_version_no `rbenv global`)
__rbenv_ps1() {
    local current_version=$(__rbenv_version_no `rbenv version`)
    if [ $__rbenv_global_version != $current_version ]; then
        echo $current_version
    fi
}
append_to_prompt '$(__rbenv_ps1)'

