#!/bin/bash

export NODE_PATH="/usr/local/lib/node_modules"

# NPM
add_to_path "/usr/local/share/npm/bin"

alias watch.vows="watchr $HOME/local/bin/vows.watchr"
alias continuously.run.jasmine.specs="watchr $HOME/local/bin/jasmine-node.watchr"

