#!/bin/bash

_brew_rm_completion ()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $(compgen -W "$(\ls $(brew --cellar))" -- ${cur}) )
}

complete -o bashdefault -o default -F _brew_rm_completion brew-rm-formula-and-orphaned-deps
