#!/bin/bash

__build_prompt() {
    PS1="${TITLEBAR}\n${line1}\n${line2}"
}

TITLEBAR="\033]2;\W\007"
line1="${green}[ \w ]${end_color}"
line2="$ "

__build_prompt

function append_to_prompt() {
    while (( "$#" )); do
        line1="$line1 $1"
        shift
    done
    __build_prompt
}
