#!/bin/bash

function __deref() {
    link="$1"
    while [ -h "$link" ]; do
        link=`readlink "$link"`
    done
    echo "$link"
}

function follow() {
    target=$(__deref "$1")
    container=$(dirname "$target")
    cd "$container"
}

function follow_executable() {
    target=$(which "$1")
    follow "$target"
}

function less_executable() {
    target=$(which "$1")
    less "$target"
}

alias fe=follow_executable
complete -c fe

alias le=less_executable
complete -c le
