#!/bin/bash

function __deref() {
    link="$1"
    while [ -h "$link" ]; do
        link=`readlink "$link"`
    done
    echo "$link"
}

function follow() {
    target=$(__deref "$1")
    container=$(dirname "$target")
    cd "$container"
}

function follow_executable() {
    target=$(which "$1")
    follow "$target"
}

complete -c follow_executable

