#!/bin/bash

# Calling `cd` once allows to use `cd -` to go back
function up() {
    suppliedLevelsCount=$(echo ${1} | awk '/[0-9]+/')
    levelsCount=${suppliedLevelsCount:-1}
    target=""
    for ((level=0; level<levelsCount; level++)); do
        target="../$target"
    done
    cd $target
}


alias bd=". bd -s"
